### ISSUE TITLE
Add support for additional cipher suites

### ISSUE THREAD

**Issue by jgillula** [EFForg/starttls-check#30]
We've gotten at least one report that someone's MTA only supports the following cipher suites:
* ECDHE-RSA-AES256-GCM-SHA384
* ECDHE-RSA-CHACHA20-POLY1305
We should add these to the ones the STARTTLS Checker supports, if it's not too much work?

**Comment by sydneyli** [comment]
The checker, by default, should be agnostic to what ciphersuites used, and it seems like we should inherit support of both from go's [tls library](https://golang.org/src/crypto/tls/cipher_suites.go). I'll investigate this further.

**Comment by vbrown608** [comment]
Added a test for this in #34
