### ISSUE TITLE
Allow any TLS version for STARTTLS check

### ISSUE THREAD

**Issue by vbrown608** [EFForg/starttls-check#36]
From the tls package docs:
```
// MinVersion contains the minimum SSL/TLS version that is acceptable.
// If zero, then TLS 1.0 is taken as the minimum.
```
By my reading that means the STARTTLS check will fail if the server has STARTTLS enabled but is using SSLv2/3 (this is borne out by adding a test). Since we return if STARTTLS fails, the checker won't reach the version test and the result might be a bit confusing.

We may want to specify the lowest possible min version for the STARTTLS check to avoid a confusing failure - then we can catch the issue in the version check.

**Comment by sydneyli** [comment]
Maybe we can just initiate the original connection with a lower `MinVersion` then?

**Comment by vbrown608** [comment]
Yeah, I think that would do the trick!
